# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\"8\n\x0eInnerMapEntry1\x12\x11\n\tinner_key\x18\x01 \x01(\t\x12\x13\n\x0binner_value\x18\x02 \x01(\t\"G\n\x0eOuterMapEntry1\x12\x11\n\touter_key\x18\x01 \x01(\t\x12\"\n\tinner_map\x18\x02 \x03(\x0b\x32\x0f.InnerMapEntry1\"8\n\x0eInnerMapEntry2\x12\x11\n\tinner_key\x18\x01 \x01(\t\x12\x13\n\x0binner_value\x18\x02 \x01(\x05\"G\n\x0eOuterMapEntry2\x12\x11\n\touter_key\x18\x01 \x01(\t\x12\"\n\tinner_map\x18\x02 \x03(\x0b\x32\x0f.InnerMapEntry2\"H\n\x0fInnerMapEntry20\x12\x11\n\tinner_key\x18\x01 \x01(\t\x12\"\n\tinner_map\x18\x02 \x03(\x0b\x32\x0f.InnerMapEntry1\"H\n\x0eOuterMapEntry3\x12\x11\n\touter_key\x18\x01 \x01(\t\x12#\n\tinner_map\x18\x02 \x03(\x0b\x32\x10.InnerMapEntry20\"8\n\x0eInnerMapEntry_\x12\x11\n\tinner_key\x18\x01 \x01(\t\x12\x13\n\x0binner_value\x18\x02 \x01(\t\"\x9a\x01\n\x0fMiddleMapEntry_\x12\x12\n\nmiddle_key\x18\x01 \x01(\t\x12\x31\n\tinner_map\x18\x02 \x03(\x0b\x32\x1e.MiddleMapEntry_.InnerMapEntry\x1a@\n\rInnerMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.InnerMapEntry_:\x02\x38\x01\"\x9b\x01\n\x0eOuterMapEntry_\x12\x11\n\touter_key\x18\x01 \x01(\t\x12\x32\n\nmiddle_map\x18\x02 \x03(\x0b\x32\x1e.OuterMapEntry_.MiddleMapEntry\x1a\x42\n\x0eMiddleMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.MiddleMapEntry_:\x02\x38\x01\"\xe9\x01\n\x04\x44\x61ta\x12\x12\n\nsubject_id\x18\x01 \x01(\t\x12\x19\n\x11num_conversations\x18\x02 \x01(\x05\x12#\n\nouter_map1\x18\x03 \x03(\x0b\x32\x0f.OuterMapEntry1\x12#\n\nouter_map2\x18\x04 \x03(\x0b\x32\x0f.OuterMapEntry2\x12&\n\touter_map\x18\x05 \x03(\x0b\x32\x13.Data.OuterMapEntry\x1a@\n\rOuterMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.OuterMapEntry_:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MIDDLEMAPENTRY__INNERMAPENTRY']._options = None
  _globals['_MIDDLEMAPENTRY__INNERMAPENTRY']._serialized_options = b'8\001'
  _globals['_OUTERMAPENTRY__MIDDLEMAPENTRY']._options = None
  _globals['_OUTERMAPENTRY__MIDDLEMAPENTRY']._serialized_options = b'8\001'
  _globals['_DATA_OUTERMAPENTRY']._options = None
  _globals['_DATA_OUTERMAPENTRY']._serialized_options = b'8\001'
  _globals['_INNERMAPENTRY1']._serialized_start=14
  _globals['_INNERMAPENTRY1']._serialized_end=70
  _globals['_OUTERMAPENTRY1']._serialized_start=72
  _globals['_OUTERMAPENTRY1']._serialized_end=143
  _globals['_INNERMAPENTRY2']._serialized_start=145
  _globals['_INNERMAPENTRY2']._serialized_end=201
  _globals['_OUTERMAPENTRY2']._serialized_start=203
  _globals['_OUTERMAPENTRY2']._serialized_end=274
  _globals['_INNERMAPENTRY20']._serialized_start=276
  _globals['_INNERMAPENTRY20']._serialized_end=348
  _globals['_OUTERMAPENTRY3']._serialized_start=350
  _globals['_OUTERMAPENTRY3']._serialized_end=422
  _globals['_INNERMAPENTRY_']._serialized_start=424
  _globals['_INNERMAPENTRY_']._serialized_end=480
  _globals['_MIDDLEMAPENTRY_']._serialized_start=483
  _globals['_MIDDLEMAPENTRY_']._serialized_end=637
  _globals['_MIDDLEMAPENTRY__INNERMAPENTRY']._serialized_start=573
  _globals['_MIDDLEMAPENTRY__INNERMAPENTRY']._serialized_end=637
  _globals['_OUTERMAPENTRY_']._serialized_start=640
  _globals['_OUTERMAPENTRY_']._serialized_end=795
  _globals['_OUTERMAPENTRY__MIDDLEMAPENTRY']._serialized_start=729
  _globals['_OUTERMAPENTRY__MIDDLEMAPENTRY']._serialized_end=795
  _globals['_DATA']._serialized_start=798
  _globals['_DATA']._serialized_end=1031
  _globals['_DATA_OUTERMAPENTRY']._serialized_start=967
  _globals['_DATA_OUTERMAPENTRY']._serialized_end=1031
# @@protoc_insertion_point(module_scope)
